name: CI

on:
  push:
    branches: [main, master, alpha, beta, next, next-major, '*.x', '*.*.x']
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  id-token: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/base.yml
    secrets: inherit
